import type {
  AccommodationAreaRecommendation,
  BundleCourse,
  MapCandidate,
  Place,
  RouteDraft,
  Trip,
  TripPlanSnapshot,
  UserPlaceSelection,
} from "./types";

export const taipeiTrip = {
  tripId: "trip-taipei-3n4d-demo",
  destination: {
    destinationId: "taipei",
    city: "Taipei",
    country: "Taiwan",
    displayName: "Taipei, Taiwan",
  },
  startDate: "2026-10-10",
  endDate: "2026-10-13",
  durationDays: 4,
  companionCount: 2,
  travelStyles: ["first_time_free_travel", "classic_landmarks", "food_focused"],
  accommodationStatus: "needed",
  selectedAccommodationArea: "ximending-main-station",
} as const satisfies Trip;

export const taipeiPlaces = [
  {
    placeId: "taipei-101-observatory",
    name: "Taipei 101 Observatory",
    category: "landmark",
    area: "Xinyi",
    coordinates: { lat: 25.033964, lng: 121.564468 },
    openingHours: { note: "Usually open from late morning to evening." },
    recommendedTimeTags: ["afternoon", "sunset", "evening"],
    averageStayMinutes: 120,
    difficulty: "easy",
    beginnerScore: 95,
    weatherSensitivity: "indoor",
    timeSensitivity: "high",
    priceLevel: "medium",
    source: "sample_curated",
    confidenceScore: 0.95,
    summary: "Classic first-time Taipei skyline stop with simple transit access.",
    recommendationReason:
      "Works well near the start of the trip because it gives an immediate city overview.",
  },
  {
    placeId: "longshan-temple",
    name: "Longshan Temple",
    category: "temple",
    area: "Wanhua",
    coordinates: { lat: 25.037162, lng: 121.4999 },
    openingHours: { note: "Open daily with the most atmosphere in the evening." },
    recommendedTimeTags: ["morning", "evening"],
    averageStayMinutes: 60,
    difficulty: "easy",
    beginnerScore: 90,
    weatherSensitivity: "all_weather",
    timeSensitivity: "medium",
    priceLevel: "free",
    source: "sample_curated",
    confidenceScore: 0.91,
    summary: "Historic temple that anchors the Wanhua and Ximending area.",
    recommendationReason:
      "Pairs naturally with Ximending and gives cultural context without a hard schedule.",
  },
  {
    placeId: "ximending",
    name: "Ximending",
    category: "neighborhood",
    area: "Wanhua",
    coordinates: { lat: 25.042081, lng: 121.508303 },
    openingHours: { note: "Best from afternoon through late evening." },
    recommendedTimeTags: ["afternoon", "evening"],
    averageStayMinutes: 150,
    difficulty: "easy",
    beginnerScore: 92,
    weatherSensitivity: "all_weather",
    timeSensitivity: "low",
    priceLevel: "low",
    source: "sample_curated",
    confidenceScore: 0.9,
    summary: "Easy food, shopping, and first-night wandering base.",
    recommendationReason:
      "Good low-pressure first evening because it stays lively and is close to many hotels.",
  },
  {
    placeId: "shilin-night-market",
    name: "Shilin Night Market",
    category: "market",
    area: "Shilin",
    coordinates: { lat: 25.088054, lng: 121.524091 },
    openingHours: { note: "Most useful from early evening." },
    recommendedTimeTags: ["evening"],
    averageStayMinutes: 120,
    difficulty: "moderate",
    beginnerScore: 86,
    weatherSensitivity: "rain_sensitive",
    timeSensitivity: "high",
    priceLevel: "low",
    source: "sample_curated",
    confidenceScore: 0.88,
    summary: "Large night market with many beginner-friendly food choices.",
    recommendationReason:
      "Adds flexible evening energy without forcing a fixed dinner reservation.",
  },
  {
    placeId: "chiang-kai-shek-memorial-hall",
    name: "Chiang Kai-shek Memorial Hall",
    category: "landmark",
    area: "Zhongzheng",
    coordinates: { lat: 25.034611, lng: 121.521781 },
    openingHours: { note: "Large outdoor plaza, best in daylight." },
    recommendedTimeTags: ["morning", "afternoon"],
    averageStayMinutes: 90,
    difficulty: "easy",
    beginnerScore: 88,
    weatherSensitivity: "outdoor",
    timeSensitivity: "medium",
    priceLevel: "free",
    source: "sample_curated",
    confidenceScore: 0.89,
    summary: "Spacious landmark stop with simple MRT access.",
    recommendationReason:
      "Fits a relaxed morning route and keeps the day from becoming transit-heavy.",
  },
  {
    placeId: "daan-forest-park",
    name: "Daan Forest Park",
    category: "nature",
    area: "Daan",
    coordinates: { lat: 25.031735, lng: 121.53554 },
    openingHours: { note: "Open all day." },
    recommendedTimeTags: ["morning", "afternoon"],
    averageStayMinutes: 75,
    difficulty: "easy",
    beginnerScore: 82,
    weatherSensitivity: "rain_sensitive",
    timeSensitivity: "low",
    priceLevel: "free",
    source: "sample_curated",
    confidenceScore: 0.82,
    summary: "A calm reset between dense city stops.",
    recommendationReason:
      "Useful as a rest candidate when the plan needs a softer block.",
  },
  {
    placeId: "tamsui-riverside",
    name: "Tamsui Riverside",
    category: "neighborhood",
    area: "Tamsui",
    coordinates: { lat: 25.171012, lng: 121.440716 },
    openingHours: { note: "Best late afternoon through sunset." },
    recommendedTimeTags: ["afternoon", "sunset"],
    averageStayMinutes: 180,
    difficulty: "moderate",
    beginnerScore: 84,
    weatherSensitivity: "rain_sensitive",
    timeSensitivity: "high",
    priceLevel: "low",
    source: "sample_curated",
    confidenceScore: 0.86,
    summary: "Riverside walk, snacks, and sunset without complex planning.",
    recommendationReason:
      "Works as a half-day route that still leaves the morning open.",
  },
  {
    placeId: "beitou-hot-spring-museum",
    name: "Beitou Hot Spring Museum",
    category: "museum",
    area: "Beitou",
    coordinates: { lat: 25.136821, lng: 121.507596 },
    openingHours: { note: "Daytime visit; check weekly closure before real use." },
    recommendedTimeTags: ["morning", "afternoon"],
    averageStayMinutes: 75,
    difficulty: "easy",
    beginnerScore: 80,
    weatherSensitivity: "indoor",
    timeSensitivity: "medium",
    priceLevel: "free",
    source: "sample_curated",
    confidenceScore: 0.8,
    summary: "Compact indoor cultural stop in the Beitou hot spring area.",
    recommendationReason:
      "Good rainy-day swap or a lighter alternative to a full north coast day.",
  },
  {
    placeId: "yehliu-geopark",
    name: "Yehliu Geopark",
    category: "day_trip",
    area: "New Taipei North Coast",
    coordinates: { lat: 25.207, lng: 121.6908 },
    openingHours: { note: "Daylight outdoor visit; weather matters." },
    recommendedTimeTags: ["morning", "afternoon"],
    averageStayMinutes: 120,
    difficulty: "moderate",
    beginnerScore: 78,
    weatherSensitivity: "rain_sensitive",
    timeSensitivity: "high",
    priceLevel: "low",
    source: "sample_curated",
    confidenceScore: 0.84,
    summary: "North coast rock formations often bundled with Shifen and Jiufen.",
    recommendationReason:
      "Best handled as part of a bundled day because standalone transit is high-friction.",
  },
  {
    placeId: "shifen-waterfall",
    name: "Shifen Waterfall",
    category: "day_trip",
    area: "Pingxi",
    coordinates: { lat: 25.049833, lng: 121.787115 },
    openingHours: { note: "Daylight visit; leave buffer for train timing." },
    recommendedTimeTags: ["afternoon"],
    averageStayMinutes: 90,
    difficulty: "moderate",
    beginnerScore: 76,
    weatherSensitivity: "rain_sensitive",
    timeSensitivity: "high",
    priceLevel: "low",
    source: "sample_curated",
    confidenceScore: 0.82,
    summary: "Scenic stop that benefits from route bundling.",
    recommendationReason:
      "Pairs with Yehliu and Jiufen when the user accepts a higher movement day.",
  },
  {
    placeId: "jiufen-old-street",
    name: "Jiufen Old Street",
    category: "day_trip",
    area: "Ruifang",
    coordinates: { lat: 25.109777, lng: 121.844236 },
    openingHours: { note: "Best afternoon to early evening." },
    recommendedTimeTags: ["afternoon", "sunset", "evening"],
    averageStayMinutes: 150,
    difficulty: "moderate",
    beginnerScore: 80,
    weatherSensitivity: "rain_sensitive",
    timeSensitivity: "high",
    priceLevel: "low",
    source: "sample_curated",
    confidenceScore: 0.86,
    summary: "Atmospheric hillside old street for a memorable day-trip finish.",
    recommendationReason:
      "Strong ending point for the north coast day, but should not be overpacked.",
  },
  {
    placeId: "yongkang-street",
    name: "Yongkang Street",
    category: "food",
    area: "Daan",
    coordinates: { lat: 25.032969, lng: 121.529883 },
    openingHours: { note: "Useful from lunch through evening." },
    recommendedTimeTags: ["lunch", "afternoon", "evening"],
    averageStayMinutes: 120,
    difficulty: "easy",
    beginnerScore: 89,
    weatherSensitivity: "all_weather",
    timeSensitivity: "medium",
    priceLevel: "medium",
    source: "sample_curated",
    confidenceScore: 0.87,
    summary: "Food and cafe area that bridges central route blocks.",
    recommendationReason:
      "Good flexible meal anchor near Daan and Dongmen accommodation options.",
  },
] as const satisfies readonly Place[];

export const taipeiUserSelections = [
  {
    selectionId: "selection-101",
    tripId: taipeiTrip.tripId,
    placeId: "taipei-101-observatory",
    selectionType: "must_go",
    priority: 1,
    userNote: "First Taipei skyline stop.",
  },
  {
    selectionId: "selection-jiufen",
    tripId: taipeiTrip.tripId,
    placeId: "jiufen-old-street",
    selectionType: "must_go",
    priority: 2,
  },
  {
    selectionId: "selection-beitou",
    tripId: taipeiTrip.tripId,
    placeId: "beitou-hot-spring-museum",
    selectionType: "interested",
    priority: 3,
    userNote: "Use as rainy-day backup.",
  },
  {
    selectionId: "selection-shilin",
    tripId: taipeiTrip.tripId,
    placeId: "shilin-night-market",
    selectionType: "interested",
    priority: 4,
  },
] as const satisfies readonly UserPlaceSelection[];

export const taipeiBundleCourses = [
  {
    courseId: "yehliu-shifen-jiufen-day",
    destination: "taipei",
    title: "Yehliu, Shifen, Jiufen day course",
    type: "full_day",
    durationMinutes: 600,
    difficulty: "high",
    beginnerScore: 76,
    transportComplexity: 8,
    freeTravelScore: 72,
    tourRecommendationScore: 88,
    includedPlaceIds: ["yehliu-geopark", "shifen-waterfall", "jiufen-old-street"],
    recommendedTimeBlock: "morning",
    recommendedDayPosition: 3,
    affiliateAvailable: false,
    recommendedReason:
      "The stops are high-value but transit-heavy, so bundling prevents overplanning.",
  },
  {
    courseId: "tamsui-sunset-half-day",
    destination: "taipei",
    title: "Tamsui sunset half-day course",
    type: "half_day",
    durationMinutes: 300,
    difficulty: "moderate",
    beginnerScore: 84,
    transportComplexity: 4,
    freeTravelScore: 86,
    tourRecommendationScore: 45,
    includedPlaceIds: ["tamsui-riverside"],
    recommendedTimeBlock: "afternoon",
    recommendedDayPosition: 2,
    affiliateAvailable: false,
    recommendedReason:
      "A simple MRT-based half day that gives the route a clear sunset moment.",
  },
  {
    courseId: "taipei-night-market-food-route",
    destination: "taipei",
    title: "Taipei night market food route",
    type: "food_route",
    durationMinutes: 180,
    difficulty: "easy",
    beginnerScore: 88,
    transportComplexity: 3,
    freeTravelScore: 90,
    tourRecommendationScore: 35,
    includedPlaceIds: ["shilin-night-market", "ximending"],
    recommendedTimeBlock: "evening",
    recommendedDayPosition: 1,
    affiliateAvailable: false,
    recommendedReason:
      "Keeps food exploration flexible while giving first-time travelers a clear evening option.",
  },
] as const satisfies readonly BundleCourse[];

export const taipeiAccommodationAreas = [
  {
    areaId: "ximending-main-station",
    destination: "taipei",
    name: "Ximending / Taipei Main Station",
    summary: "Best all-around base for first-time visitors and airport rail access.",
    averageAccessScore: 92,
    airportStationAccessScore: 96,
    nightReturnConvenienceScore: 94,
    beginnerSuitabilityScore: 95,
    travelStyleFit: ["first_time_free_travel", "classic_landmarks", "food_focused"],
    recommendedReason:
      "Central, forgiving at night, and close to the first-day Wanhua route.",
  },
  {
    areaId: "zhongshan",
    destination: "taipei",
    name: "Zhongshan",
    summary: "Calmer central base with cafes, shopping, and reliable MRT access.",
    averageAccessScore: 88,
    airportStationAccessScore: 86,
    nightReturnConvenienceScore: 90,
    beginnerSuitabilityScore: 88,
    travelStyleFit: ["slow_paced", "food_focused"],
    recommendedReason:
      "Good for travelers who want convenience without staying in the busiest area.",
  },
  {
    areaId: "daan-dongmen",
    destination: "taipei",
    name: "Daan / Dongmen",
    summary: "Food and park-friendly stay area for a slower Taipei plan.",
    averageAccessScore: 84,
    airportStationAccessScore: 78,
    nightReturnConvenienceScore: 86,
    beginnerSuitabilityScore: 84,
    travelStyleFit: ["slow_paced", "food_focused", "classic_landmarks"],
    recommendedReason:
      "Fits users who prioritize cafes, parks, and lower-pressure city blocks.",
  },
] as const satisfies readonly AccommodationAreaRecommendation[];

export const taipeiRouteDraft = [
  {
    routeId: "route-day1-afternoon-ximending",
    tripId: taipeiTrip.tripId,
    day: 1,
    timeBlock: "afternoon",
    itemType: "place",
    placeId: "longshan-temple",
    title: "Longshan Temple and Wanhua arrival walk",
    recommendedReason: "A compact arrival route near the recommended stay area.",
    travelTimeToNextMinutes: 12,
    difficultyScore: 2,
    isLocked: false,
  },
  {
    routeId: "route-day1-evening-food",
    tripId: taipeiTrip.tripId,
    day: 1,
    timeBlock: "evening",
    itemType: "bundle_course",
    courseId: "taipei-night-market-food-route",
    title: "Flexible first-night food route",
    recommendedReason: "Keeps dinner flexible after arrival.",
    travelTimeToNextMinutes: 0,
    difficultyScore: 2,
    isLocked: false,
  },
  {
    routeId: "route-day2-morning-cks",
    tripId: taipeiTrip.tripId,
    day: 2,
    timeBlock: "morning",
    itemType: "place",
    placeId: "chiang-kai-shek-memorial-hall",
    title: "Central landmark morning",
    recommendedReason: "Simple MRT access and enough space for a relaxed start.",
    travelTimeToNextMinutes: 18,
    difficultyScore: 2,
    isLocked: false,
  },
  {
    routeId: "route-day2-sunset-tamsui",
    tripId: taipeiTrip.tripId,
    day: 2,
    timeBlock: "sunset",
    itemType: "bundle_course",
    courseId: "tamsui-sunset-half-day",
    title: "Tamsui sunset half day",
    recommendedReason: "Adds a scenic block without making the whole day rigid.",
    travelTimeToNextMinutes: 0,
    difficultyScore: 4,
    isLocked: false,
  },
  {
    routeId: "route-day3-full-day-north-coast",
    tripId: taipeiTrip.tripId,
    day: 3,
    timeBlock: "morning",
    itemType: "bundle_course",
    courseId: "yehliu-shifen-jiufen-day",
    title: "North coast and old street day",
    recommendedReason: "A single bundled day prevents fragmented transit planning.",
    travelTimeToNextMinutes: 0,
    difficultyScore: 7,
    isLocked: false,
  },
  {
    routeId: "route-day4-morning-daan",
    tripId: taipeiTrip.tripId,
    day: 4,
    timeBlock: "morning",
    itemType: "place",
    placeId: "daan-forest-park",
    title: "Daan slow morning",
    recommendedReason: "A low-pressure final morning before departure.",
    travelTimeToNextMinutes: 10,
    difficultyScore: 1,
    isLocked: false,
  },
  {
    routeId: "route-day4-lunch-yongkang",
    tripId: taipeiTrip.tripId,
    day: 4,
    timeBlock: "lunch",
    itemType: "place",
    placeId: "yongkang-street",
    title: "Yongkang Street lunch buffer",
    recommendedReason: "Flexible meal block that can expand or shrink before leaving.",
    travelTimeToNextMinutes: 0,
    difficultyScore: 2,
    isLocked: false,
  },
] as const satisfies readonly RouteDraft[];

export const taipeiMapCandidates = [
  {
    candidateId: "candidate-beitou-rain",
    tripId: taipeiTrip.tripId,
    placeId: "beitou-hot-spring-museum",
    candidateType: "rainy_day",
    relatedRouteDay: 2,
    distanceFromRouteKm: 8.4,
    estimatedDetourMinutes: 45,
    recommendationReason: "Indoor-heavy backup if Tamsui weather is poor.",
    weatherCondition: "rain",
  },
  {
    candidateId: "candidate-shilin-interest",
    tripId: taipeiTrip.tripId,
    placeId: "shilin-night-market",
    candidateType: "interest",
    relatedRouteDay: 2,
    distanceFromRouteKm: 4.8,
    estimatedDetourMinutes: 25,
    recommendationReason: "Saved as an optional evening food stop.",
    weatherCondition: "evening",
  },
  {
    candidateId: "candidate-yongkang-nearby",
    tripId: taipeiTrip.tripId,
    placeId: "yongkang-street",
    candidateType: "nearby",
    relatedRouteDay: 4,
    distanceFromRouteKm: 0.9,
    estimatedDetourMinutes: 10,
    recommendationReason: "Near Daan Forest Park and easy to add for lunch.",
    weatherCondition: "any",
  },
  {
    candidateId: "candidate-daan-rest",
    tripId: taipeiTrip.tripId,
    placeId: "daan-forest-park",
    candidateType: "rest",
    relatedRouteDay: 4,
    distanceFromRouteKm: 0,
    estimatedDetourMinutes: 0,
    recommendationReason: "Use as a softer final-day buffer.",
    weatherCondition: "clear",
  },
] as const satisfies readonly MapCandidate[];

export const taipeiTripPlanSnapshot = {
  snapshotId: "snapshot-taipei-3n4d-demo-v1",
  schemaVersion: 1,
  trip: taipeiTrip,
  userSelections: taipeiUserSelections,
  selectedBundleCourseIds: [
    "taipei-night-market-food-route",
    "tamsui-sunset-half-day",
    "yehliu-shifen-jiufen-day",
  ],
  accommodationChoice: taipeiAccommodationAreas[0],
  routeDraft: taipeiRouteDraft,
  mapCandidates: taipeiMapCandidates,
  savedAt: "2026-06-30T10:00:00.000Z",
  source: "sample",
} as const satisfies TripPlanSnapshot;
